# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 90e29f31c163e97815c957b4d27a54afba52cf7ea0cb774b7c6ee9d150a9a3e018579eb13e8d81a1d44a399a48e98354200e760b3ec0f7596d592df641cc0224

test:
  secret_key_base: 810d759ecf2b68bbd9796787400c5d156f94c5ab31aa036fdbd0895ac5912a3d0c86d75aedd326fda36a41c02127178443cc8a27a48e4abab45cb2c2787507ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
